<a href="https://colab.research.google.com/github/DeepanshuSharma1607/ipl-winner-pedictor/blob/main/ipl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1603]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [1604]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "IPL_ball_by_ball_updated.csv"

# Load the latest version
df_nn = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "dgsports/ipl-ball-by-ball-2008-to-2022",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

# print("First 5 records:", df__.head())

/tmp/ipykernel_1706/2934442778.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_nn = kagglehub.load_dataset(

Using Colab cache for faster access to the 'ipl-ball-by-ball-2008-to-2022' dataset.

In [1605]:
print(df_nn.head(10))

   match_id  season  start_date                  venue  innings  ball  \
0    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   0.1
1    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   0.2
2    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   0.3
3    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   0.4
4    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   0.5
5    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   0.6
6    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   0.7
7    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   1.1
8    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   1.2
9    335982    2008  2008-04-18  M Chinnaswamy Stadium        1   1.3

            batting_team                 bowling_team      striker  \
0  Kolkata Knight Riders  Royal Challengers Bangalore   SC Ganguly
1  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum
2  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum
3  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum
4  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum
5  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum
6  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum
7  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum
8  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum
9  Kolkata Knight Riders  Royal Challengers Bangalore  BB McCullum

   non_striker  ... extras  wides  noballs  byes  legbyes  penalty  \
0  BB McCullum  ...      1    NaN      NaN   NaN      1.0      NaN
1   SC Ganguly  ...      0    NaN      NaN   NaN      NaN      NaN
2   SC Ganguly  ...      1    1.0      NaN   NaN      NaN      NaN
3   SC Ganguly  ...      0    NaN      NaN   NaN      NaN      NaN
4   SC Ganguly  ...      0    NaN      NaN   NaN      NaN      NaN
5   SC Ganguly  ...      0    NaN      NaN   NaN      NaN      NaN
6   SC Ganguly  ...      1    NaN      NaN   NaN      1.0      NaN
7   SC Ganguly  ...      0    NaN      NaN   NaN      NaN      NaN
8   SC Ganguly  ...      0    NaN      NaN   NaN      NaN      NaN
9   SC Ganguly  ...      0    NaN      NaN   NaN      NaN      NaN

   wicket_type  player_dismissed other_wicket_type other_player_dismissed
0          NaN               NaN               NaN                    NaN
1          NaN               NaN               NaN                    NaN
2          NaN               NaN               NaN                    NaN
3          NaN               NaN               NaN                    NaN
4          NaN               NaN               NaN                    NaN
5          NaN               NaN               NaN                    NaN
6          NaN               NaN               NaN                    NaN
7          NaN               NaN               NaN                    NaN
8          NaN               NaN               NaN                    NaN
9          NaN               NaN               NaN                    NaN

[10 rows x 22 columns]

In [1606]:
# df_matches.shape

In [1607]:
df_nn.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [1608]:
df_nn.shape

(243815, 22)

In [1609]:
df_nn.isnull().sum()

match_id                       0
season                         0
start_date                     0
venue                          0
innings                        0
ball                           0
batting_team                   0
bowling_team                   0
striker                        0
non_striker                    0
bowler                         0
runs_off_bat                   0
extras                         0
wides                     236163
noballs                   242797
byes                      243187
legbyes                   240037
penalty                   243813
wicket_type               231748
player_dismissed          231748
other_wicket_type         243815
other_player_dismissed    243815
dtype: int64

In [1610]:
df_nn

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243810,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.2,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243811,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.3,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243812,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.4,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243813,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.5,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243814,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.6,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1611]:

df=df_nn.copy()

In [1612]:
team_mapping = {
    # Rebranded Teams
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',

    # Successor Franchises (Optional but recommended for model logic)
    'Deccan Chargers': 'Sunrisers Hyderabad',
    'Rising Pune Supergiants': 'Rising Pune Supergiant',
    'Pune Warriors': 'Rising Pune Supergiant'
}

# Apply to both team columns
df['batting_team'] = df['batting_team'].replace(team_mapping)
df['bowling_team'] = df['bowling_team'].replace(team_mapping)

In [1613]:
df

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bengaluru,SC Ganguly,BB McCullum,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243810,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.2,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243811,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.3,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243812,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.4,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243813,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.5,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243814,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.6,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1614]:
df.shape

(243815, 22)

In [1615]:
df

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bengaluru,SC Ganguly,BB McCullum,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243810,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.2,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243811,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.3,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243812,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.4,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243813,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.5,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243814,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.6,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1616]:
df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [1617]:
print(df[['runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed']])

        runs_off_bat  extras  wides  noballs  byes  legbyes  penalty  \
0                  0       1    NaN      NaN   NaN      1.0      NaN
1                  0       0    NaN      NaN   NaN      NaN      NaN
2                  0       1    1.0      NaN   NaN      NaN      NaN
3                  0       0    NaN      NaN   NaN      NaN      NaN
4                  0       0    NaN      NaN   NaN      NaN      NaN
...              ...     ...    ...      ...   ...      ...      ...
243810             1       0    NaN      NaN   NaN      NaN      NaN
243811             1       0    NaN      NaN   NaN      NaN      NaN
243812             1       0    NaN      NaN   NaN      NaN      NaN
243813             6       0    NaN      NaN   NaN      NaN      NaN
243814             4       0    NaN      NaN   NaN      NaN      NaN

       wicket_type player_dismissed  other_wicket_type  other_player_dismissed
0              NaN              NaN                NaN                     NaN
1              NaN              NaN                NaN                     NaN
2              NaN              NaN                NaN                     NaN
3              NaN              NaN                NaN                     NaN
4              NaN              NaN                NaN                     NaN
...            ...              ...                ...                     ...
243810         NaN              NaN                NaN                     NaN
243811         NaN              NaN                NaN                     NaN
243812         NaN              NaN                NaN                     NaN
243813         NaN              NaN                NaN                     NaN
243814         NaN              NaN                NaN                     NaN

[243815 rows x 11 columns]

In [1618]:
cols_to_fix = ['runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes', 'penalty']
df[cols_to_fix] = df[cols_to_fix].fillna(0)

df['curr_ball_runs'] = df['runs_off_bat'] + df['extras']
total_score = df.groupby(['match_id', 'innings', 'batting_team'])['curr_ball_runs'].cumsum().reset_index()

In [1619]:
df['team_runs'] = df.groupby(['match_id','batting_team'])['curr_ball_runs'].cumsum()
df['team_runs'] = df.groupby(['match_id','batting_team'])['team_runs'].shift(1).fillna(0)

In [1620]:
df['first_innings_runs'] = np.where(df['innings'] == 1, df['team_runs'], 0)

df['second_innings_runs'] = np.where(df['innings'] == 2, df['team_runs'], 0)

In [1621]:
df

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,curr_ball_runs,team_runs,first_innings_runs,second_innings_runs
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bengaluru,SC Ganguly,BB McCullum,...,1.0,0.0,NaN,NaN,NaN,NaN,1,0.0,0.0,0.0
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0.0,0.0,NaN,NaN,NaN,NaN,0,1.0,1.0,0.0
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0.0,0.0,NaN,NaN,NaN,NaN,1,1.0,1.0,0.0
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0.0,0.0,NaN,NaN,NaN,NaN,0,2.0,2.0,0.0
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0.0,0.0,NaN,NaN,NaN,NaN,0,2.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243810,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.2,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,0.0,0.0,NaN,NaN,NaN,NaN,1,158.0,0.0,158.0
243811,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.3,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0.0,0.0,NaN,NaN,NaN,NaN,1,159.0,0.0,159.0
243812,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.4,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,0.0,0.0,NaN,NaN,NaN,NaN,1,160.0,0.0,160.0
243813,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.5,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0.0,0.0,NaN,NaN,NaN,NaN,6,161.0,0.0,161.0
243814,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.6,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0.0,0.0,NaN,NaN,NaN,NaN,4,167.0,0.0,167.0

In [1622]:
df['is_wicket']=df['player_dismissed'].notna().astype(int)

In [1623]:
df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'curr_ball_runs', 'team_runs',
       'first_innings_runs', 'second_innings_runs', 'is_wicket'],
      dtype='object')

In [1624]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243815 entries, 0 to 243814
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   match_id                243815 non-null  int64
 1   season                  243815 non-null  int64
 2   start_date              243815 non-null  object
 3   venue                   243815 non-null  object
 4   innings                 243815 non-null  int64
 5   ball                    243815 non-null  float64
 6   batting_team            243815 non-null  object
 7   bowling_team            243815 non-null  object
 8   striker                 243815 non-null  object
 9   non_striker             243815 non-null  object
 10  bowler                  243815 non-null  object
 11  runs_off_bat            243815 non-null  int64
 12  extras                  243815 non-null  int64
 13  wides                   243815 non-null  float64
 14  noballs                 243815 non-null  float64
 15  byes                    243815 non-null  float64
 16  legbyes                 243815 non-null  float64
 17  penalty                 243815 non-null  float64
 18  wicket_type             12067 non-null   object
 19  player_dismissed        12067 non-null   object
 20  other_wicket_type       0 non-null       float64
 21  other_player_dismissed  0 non-null       float64
 22  curr_ball_runs          243815 non-null  int64
 23  team_runs               243815 non-null  float64
 24  first_innings_runs      243815 non-null  float64
 25  second_innings_runs     243815 non-null  float64
 26  is_wicket               243815 non-null  int64
dtypes: float64(11), int64(7), object(9)
memory usage: 50.2+ MB

In [1625]:
df

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,curr_ball_runs,team_runs,first_innings_runs,second_innings_runs,is_wicket
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bengaluru,SC Ganguly,BB McCullum,...,0.0,NaN,NaN,NaN,NaN,1,0.0,0.0,0.0,0
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0.0,NaN,NaN,NaN,NaN,0,1.0,1.0,0.0,0
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0.0,NaN,NaN,NaN,NaN,1,1.0,1.0,0.0,0
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0.0,NaN,NaN,NaN,NaN,0,2.0,2.0,0.0,0
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0.0,NaN,NaN,NaN,NaN,0,2.0,2.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243810,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.2,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,0.0,NaN,NaN,NaN,NaN,1,158.0,0.0,158.0,0
243811,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.3,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0.0,NaN,NaN,NaN,NaN,1,159.0,0.0,159.0,0
243812,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.4,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,0.0,NaN,NaN,NaN,NaN,1,160.0,0.0,160.0,0
243813,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.5,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0.0,NaN,NaN,NaN,NaN,6,161.0,0.0,161.0,0
243814,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.6,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,0.0,NaN,NaN,NaN,NaN,4,167.0,0.0,167.0,0

In [1626]:
final_scores = df[df['innings'] == 1].groupby('match_id')['team_runs'].max()
df = df.merge(final_scores.rename('target'), on='match_id')
df['target'] = np.where(df['innings'] == 2, df['target'] + 1, 0)

In [1627]:
df['over'] = df['ball'].astype(str).str.split('.').str[0].astype(int)
df['ball_in_over'] = df['ball'].astype(str).str.split('.').str[1].astype(int)

In [1628]:
df['ball_in_over'] = df['ball_in_over'].clip(upper=6)
df['balls_bowled'] = df['over'] * 6 + df['ball_in_over']

In [1629]:
df['runs_to_win'] = np.where(
    df['innings'] == 2,
    df['target'] - df['team_runs'],
    0
)

In [1630]:
df['runs_to_win'] = np.where(
    df['innings'] == 2,
    df['target'] - df['team_runs'],
    0
)

In [1631]:
balls_remaining = (120 - df['balls_bowled']).clip(lower=0)

In [1632]:
df['curr_run_rate'] = np.where(
    df['balls_bowled'] == 0, 0,
    (df['team_runs'] * 6) / df['balls_bowled']
)

In [1633]:
df['req_run_rate'] = np.where(
    balls_remaining == 0,
    np.inf,
    (df['runs_to_win'] * 6) / balls_remaining
)
df['req_run_rate'] = df['req_run_rate'].clip(0, 36)

In [1634]:
df['req_run_rate'] = df['req_run_rate'].replace(np.inf, 100)

In [1635]:
df['crr_rrr_ratio'] = df['curr_run_rate'] / df['req_run_rate'].replace(0, np.inf)

df['crr_rrr_ratio'] = df['crr_rrr_ratio'].clip(0, 10)

df.loc[df['innings'] == 1,
       ['target', 'runs_to_win', 'req_run_rate', 'crr_rrr_ratio']] = 0

In [1636]:
df['balls_remaining'] = (20 * 6) - df['balls_bowled']

In [1637]:
df['total_wickets'] = df.groupby(['match_id','innings'])['is_wicket'].cumsum()
df['total_wickets'] = df.groupby(['match_id','innings'])['total_wickets'].shift(1).fillna(0)
df['wickets_remaining'] = 10 - df['total_wickets']

In [1638]:
df

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,over,ball_in_over,balls_bowled,runs_to_win,curr_run_rate,req_run_rate,crr_rrr_ratio,balls_remaining,total_wickets,wickets_remaining
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bengaluru,SC Ganguly,BB McCullum,...,0,1,1,0.0,0.000000,0.000000,0.000000,119,0.0,10.0
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0,2,2,0.0,3.000000,0.000000,0.000000,118,0.0,10.0
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0,3,3,0.0,2.000000,0.000000,0.000000,117,0.0,10.0
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0,4,4,0.0,3.000000,0.000000,0.000000,116,0.0,10.0
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bengaluru,BB McCullum,SC Ganguly,...,0,5,5,0.0,2.400000,0.000000,0.000000,115,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243810,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.2,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,14,2,86,57.0,11.023256,10.058824,1.095879,34,5.0,5.0
243811,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.3,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,14,3,87,56.0,10.965517,10.181818,1.076970,33,5.0,5.0
243812,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.4,Chennai Super Kings,Gujarat Titans,S Dube,RA Jadeja,...,14,4,88,55.0,10.909091,10.312500,1.057851,32,5.0,5.0
243813,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.5,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,14,5,89,54.0,10.853933,10.451613,1.038494,31,5.0,5.0
243814,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,14.6,Chennai Super Kings,Gujarat Titans,RA Jadeja,S Dube,...,14,6,90,48.0,11.133333,9.600000,1.159722,30,5.0,5.0

In [1639]:
df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'curr_ball_runs', 'team_runs',
       'first_innings_runs', 'second_innings_runs', 'is_wicket', 'target',
       'over', 'ball_in_over', 'balls_bowled', 'runs_to_win', 'curr_run_rate',
       'req_run_rate', 'crr_rrr_ratio', 'balls_remaining', 'total_wickets',
       'wickets_remaining'],
      dtype='object')

In [1640]:
df['is_out'] = (df['player_dismissed'] == df['striker']).astype(int)

df['valid_ball'] = (df['wides'] == 0).astype(int)

# df['batsman_run_cum'] = df.groupby(['match_id','striker'])['runs_off_bat'].cumsum()
# df['batsman_run_cum'] = df.groupby(['match_id','striker'])['batsman_run_cum'].shift(1).fillna(0)

# df['balls_faced_cum'] = df.groupby(['match_id','striker'])['valid_ball'].cumsum()
# df['balls_faced_cum'] = df.groupby(['match_id','striker'])['balls_faced_cum'].shift(1).fillna(0)

# df['match_strike_rate'] = np.where(
#     df['balls_faced_cum'] == 0,
#     0,
#     (df['batsman_run_cum'] / df['balls_faced_cum']) * 100
# )



# df['batsman_run_cum_career'] = df.groupby('striker')['runs_off_bat'].cumsum()
# df['batsman_run_cum_career'] = df.groupby('striker')['batsman_run_cum_career'].shift(1).fillna(0)

# df['balls_faced_cum_career'] = df.groupby('striker')['valid_ball'].cumsum()
# df['balls_faced_cum_career'] = df.groupby('striker')['balls_faced_cum_career'].shift(1).fillna(0)

# df['batsman_outs_career'] = df.groupby('striker')['is_out'].cumsum()
# df['batsman_outs_career'] = df.groupby('striker')['batsman_outs_career'].shift(1).fillna(0)

# universal_runs = 50
# universal_outs = 2

# df['batting_average'] = (
#     df['batsman_run_cum_career'] + universal_runs
# ) / (
#     df['batsman_outs_career'] + universal_outs
# )


# universal_sr_runs = 100
# universal_balls = 80

# df['career_strike_rate'] = (
#     (df['batsman_run_cum_career'] + universal_sr_runs) /
#     (df['balls_faced_cum_career'] + universal_balls)
# ) * 100
# Aggregate per striker per season
season_bat = df.groupby(['season', 'striker']).agg(
    season_runs=('runs_off_bat', 'sum'),
    season_balls=('valid_ball', 'sum'),
    season_outs=('is_out', 'sum')
).reset_index().sort_values(['striker', 'season'])

# Cumsum then shift — so current season stats NOT included
season_bat['career_runs'] = season_bat.groupby('striker')['season_runs'].cumsum().shift(1).fillna(0)
season_bat['career_balls'] = season_bat.groupby('striker')['season_balls'].cumsum().shift(1).fillna(0)
season_bat['career_outs'] = season_bat.groupby('striker')['season_outs'].cumsum().shift(1).fillna(0)

# Smoothed stats
season_bat['batting_average'] = (season_bat['career_runs'] + 50) / (season_bat['career_outs'] + 2)
season_bat['career_strike_rate'] = ((season_bat['career_runs'] + 100) / (season_bat['career_balls'] + 80)) * 100

# Merge back
df = df.merge(
    season_bat[['season', 'striker', 'batting_average', 'career_strike_rate']],
    on=['season', 'striker'], how='left'
)

In [1641]:


# df['bowler_runs_conceded'] = df.groupby('bowler')['runs_off_bat'].cumsum()
# df['bowler_runs_conceded'] = df.groupby('bowler')['bowler_runs_conceded'].shift(1).fillna(0)

# df['bowler_balls_bowled'] = df.groupby('bowler')['valid_ball'].cumsum()
# df['bowler_balls_bowled'] = df.groupby('bowler')['bowler_balls_bowled'].shift(1).fillna(0)

# df['bowler_wickets_cum'] = df.groupby('bowler')['is_wicket'].cumsum()
# df['bowler_wickets_cum'] = df.groupby('bowler')['bowler_wickets_cum'].shift(1).fillna(0)



# universal_runs_conceded = 300
# universal_balls = 240
# universal_wickets = 10


# df['exp_bowler_eco'] = (
#     (df['bowler_runs_conceded'] + universal_runs_conceded) /
#     (df['bowler_balls_bowled'] + universal_balls)
# ) * 6


# df['exp_bowler_avg'] = (
#     df['bowler_runs_conceded'] + universal_runs_conceded
# ) / (
#     df['bowler_wickets_cum'] + universal_wickets
# )
# Aggregate per bowler per season
season_bowl = df.groupby(['season', 'bowler']).agg(
    season_runs_c=('runs_off_bat', 'sum'),
    season_balls_b=('valid_ball', 'sum'),
    season_wkts=('is_wicket', 'sum')
).reset_index().sort_values(['bowler', 'season'])

# Cumsum then shift — so current season NOT included
season_bowl['career_runs_c'] = season_bowl.groupby('bowler')['season_runs_c'].cumsum().shift(1).fillna(0)
season_bowl['career_balls_b'] = season_bowl.groupby('bowler')['season_balls_b'].cumsum().shift(1).fillna(0)
season_bowl['career_wkts'] = season_bowl.groupby('bowler')['season_wkts'].cumsum().shift(1).fillna(0)

# Smoothed stats
season_bowl['exp_bowler_eco'] = ((season_bowl['career_runs_c'] + 300) / (season_bowl['career_balls_b'] + 240)) * 6
season_bowl['exp_bowler_avg'] = (season_bowl['career_runs_c'] + 300) / (season_bowl['career_wkts'] + 10)

# Merge back
df = df.merge(
    season_bowl[['season', 'bowler', 'exp_bowler_eco', 'exp_bowler_avg']],
    on=['season', 'bowler'], how='left'
)

In [1642]:
df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'curr_ball_runs', 'team_runs',
       'first_innings_runs', 'second_innings_runs', 'is_wicket', 'target',
       'over', 'ball_in_over', 'balls_bowled', 'runs_to_win', 'curr_run_rate',
       'req_run_rate', 'crr_rrr_ratio', 'balls_remaining', 'total_wickets',
       'wickets_remaining', 'is_out', 'valid_ball', 'batting_average',
       'career_strike_rate', 'exp_bowler_eco', 'exp_bowler_avg'],
      dtype='object')

In [1643]:
df.shape

(243815, 44)

In [1644]:
final_scores = df.groupby(['match_id', 'innings'])['team_runs'].max().reset_index()
final_scores = final_scores.pivot(index='match_id', columns='innings', values='team_runs').reset_index()
final_scores['winner_innings'] = np.where(
    final_scores[2] > final_scores[1], 2,
    np.where(final_scores[2] < final_scores[1], 1, 0)
)

df = df.merge(final_scores[['match_id', 'winner_innings']], on='match_id', how='left')

df['result'] = np.where(
    (df['innings'] == 2) & (df['winner_innings'] == 2),
    1,
    np.where(
        (df['innings'] == 2) & (df['winner_innings'] == 1),
        0,
        -1   # tie
    )
)

In [1645]:
df.shape

(243815, 46)

In [1646]:
df.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'curr_ball_runs', 'team_runs',
       'first_innings_runs', 'second_innings_runs', 'is_wicket', 'target',
       'over', 'ball_in_over', 'balls_bowled', 'runs_to_win', 'curr_run_rate',
       'req_run_rate', 'crr_rrr_ratio', 'balls_remaining', 'total_wickets',
       'wickets_remaining', 'is_out', 'valid_ball', 'batting_average',
       'career_strike_rate', 'exp_bowler_eco', 'exp_bowler_avg',
       'winner_innings', 'result'],
      dtype='object')

In [1647]:
drop_list = [
    'match_id', 'start_date', 'runs_off_bat', 'extras', 'wides',
    'noballs', 'byes', 'legbyes', 'penalty', 'curr_ball_runs',
    'wicket_type', 'player_dismissed', 'other_wicket_type',
    'other_player_dismissed', 'is_wicket', 'is_out', 'winner_innings',
    'ball', 'over', 'ball_in_over', 'balls_bowled', 'valid_ball',
    'team_runs', 'first_innings_runs', 'second_innings_runs', 'target',
    # 'batsman_run_cum', 'balls_faced_cum',
    'total_wickets'
]
df = df.drop(columns=drop_list)

In [1648]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243815 entries, 0 to 243814
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   season              243815 non-null  int64
 1   venue               243815 non-null  object
 2   innings             243815 non-null  int64
 3   batting_team        243815 non-null  object
 4   bowling_team        243815 non-null  object
 5   striker             243815 non-null  object
 6   non_striker         243815 non-null  object
 7   bowler              243815 non-null  object
 8   runs_to_win         243815 non-null  float64
 9   curr_run_rate       243815 non-null  float64
 10  req_run_rate        243815 non-null  float64
 11  crr_rrr_ratio       243815 non-null  float64
 12  balls_remaining     243815 non-null  int64
 13  wickets_remaining   243815 non-null  float64
 14  batting_average     243815 non-null  float64
 15  career_strike_rate  243815 non-null  float64
 16  exp_bowler_eco      243815 non-null  float64
 17  exp_bowler_avg      243815 non-null  float64
 18  result              243815 non-null  int64
dtypes: float64(9), int64(4), object(6)
memory usage: 35.3+ MB

In [1649]:
df['pressure'] = df['req_run_rate'] - df['curr_run_rate']

In [1650]:
df = df[df['innings'] <= 2]
df = df[df['result'] != -1]

In [1651]:
df.describe()

,season,innings,runs_to_win,curr_run_rate,req_run_rate,crr_rrr_ratio,balls_remaining,wickets_remaining,batting_average,career_strike_rate,exp_bowler_eco,exp_bowler_avg,result,pressure
count,103412.00000,103412.0,103412.000000,103412.000000,103412.000000,103412.000000,103412.000000,103412.000000,103412.000000,103412.000000,103412.000000,103412.000000,103412.000000,103412.000000
mean,2015.64450,2.0,94.912012,7.163956,10.373683,0.902514,62.609175,7.505657,27.764467,128.511521,7.524946,26.716769,0.274813,3.209728
std,4.63419,0.0,50.219457,2.264983,5.882801,0.889135,33.544251,2.177735,8.477640,12.360424,0.506973,4.983105,0.446422,6.330184
min,2008.00000,2.0,-15.000000,0.000000,0.000000,0.000000,0.000000,1.000000,5.428571,82.530120,5.914198,14.846154,0.000000,-17.582609
25%,2012.00000,2.0,55.000000,6.000000,7.451613,0.518094,34.000000,6.000000,22.000000,121.111111,7.238938,23.048780,0.000000,-0.296682
50%,2015.00000,2.0,94.000000,7.317073,9.148515,0.748971,63.000000,8.000000,27.879310,127.231565,7.567797,25.916667,0.000000,2.291533
75%,2020.00000,2.0,133.000000,8.538462,11.361702,1.029595,92.000000,9.000000,32.788462,135.235732,7.860759,30.090909,1.000000,5.340095
max,2023.00000,2.0,264.000000,24.000000,36.000000,10.000000,119.000000,10.000000,67.333333,180.335731,8.949153,44.571429,1.000000,31.565217

In [1652]:
df = df[df['innings'] == 2]
df = df[df['runs_to_win'] >= 0]
df = df[df['balls_remaining'] > 0]

In [1653]:
df.describe()

,season,innings,runs_to_win,curr_run_rate,req_run_rate,crr_rrr_ratio,balls_remaining,wickets_remaining,batting_average,career_strike_rate,exp_bowler_eco,exp_bowler_avg,result,pressure
count,102579.000000,102579.0,102579.000000,102579.000000,102579.000000,102579.000000,102579.000000,102579.000000,102579.000000,102579.000000,102579.000000,102579.000000,102579.000000,102579.000000
mean,2015.643407,2.0,95.589048,7.155494,10.278940,0.908755,63.076858,7.532029,27.799327,128.539862,7.523958,26.715360,0.273370,3.123446
std,4.634391,0.0,49.827068,2.269089,5.592451,0.889970,33.260688,2.156706,8.467761,12.353729,0.507339,4.983616,0.445691,6.069816
min,2008.000000,2.0,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,5.428571,82.530120,5.914198,14.846154,0.000000,-17.582609
25%,2012.000000,2.0,56.000000,6.000000,7.462185,0.523824,35.000000,6.000000,22.074728,121.132540,7.233379,23.048780,0.000000,-0.285315
50%,2015.000000,2.0,95.000000,7.307692,9.142857,0.752874,64.000000,8.000000,28.000000,127.231565,7.567416,25.916667,0.000000,2.281330
75%,2020.000000,2.0,133.000000,8.531250,11.320755,1.033104,92.000000,9.000000,32.788462,135.266084,7.858407,30.090909,1.000000,5.296703
max,2023.000000,2.0,264.000000,24.000000,36.000000,10.000000,119.000000,10.000000,67.333333,180.335731,8.949153,44.571429,1.000000,31.565217

In [1654]:
train = df[df['season'] <= 2020]        # 2008-2020 → 13 seasons
cv    = df[(df['season'] >= 2021) & (df['season'] <= 2022)]  # 2021-2022 → 2 seasons
test  = df[df['season'] == 2023]        # 2023 → 1 season

In [1655]:
x_train = train.drop('result', axis=1)
y_train = train['result']

x_cv = cv.drop('result', axis=1)
y_cv = cv['result']

x_test = test.drop('result', axis=1)
y_test = test['result']

In [1656]:
print("Train:", train['season'].unique())
print("CV:", cv['season'].unique())
print("Test:", test['season'].unique())

Train: [2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]
CV: [2021 2022]
Test: [2023]

In [1657]:
x_train = x_train.drop(columns=['season'])
x_cv = x_cv.drop(columns=['season'])
x_test = x_test.drop(columns=['season'])

In [1658]:
# from sklearn.model_selection import train_test_split
# x_train,x_temp,y_train,y_temp=train_test_split(df, y, test_size=0.4, random_state=42)
# x_cv,x_test,y_cv,y_test=train_test_split(x_temp, y_temp,test_size=0.5, random_state=42)

In [1659]:
x_train = x_train.drop(columns=['innings'])
x_cv = x_cv.drop(columns=['innings'])
x_test = x_test.drop(columns=['innings'])

In [1660]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81408 entries, 124 to 193615
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   venue               81408 non-null  object
 1   batting_team        81408 non-null  object
 2   bowling_team        81408 non-null  object
 3   striker             81408 non-null  object
 4   non_striker         81408 non-null  object
 5   bowler              81408 non-null  object
 6   runs_to_win         81408 non-null  float64
 7   curr_run_rate       81408 non-null  float64
 8   req_run_rate        81408 non-null  float64
 9   crr_rrr_ratio       81408 non-null  float64
 10  balls_remaining     81408 non-null  int64
 11  wickets_remaining   81408 non-null  float64
 12  batting_average     81408 non-null  float64
 13  career_strike_rate  81408 non-null  float64
 14  exp_bowler_eco      81408 non-null  float64
 15  exp_bowler_avg      81408 non-null  float64
 16  pressure            81408 non-null  float64
dtypes: float64(10), int64(1), object(6)
memory usage: 11.2+ MB

In [1662]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder,TargetEncoder,StandardScaler
from sklearn.linear_model import LogisticRegression
# target_encode=['striker','bowler','non_striker']
nominal_cols=['batting_team','bowling_team']#,'venue']
numeric_cols=['runs_to_win', 'curr_run_rate', 'req_run_rate', 'crr_rrr_ratio',
              'balls_remaining', 'wickets_remaining',
              #'match_strike_rate',
              'batting_average','pressure',
              'exp_bowler_eco', 'exp_bowler_avg']
print("Infinite values remaining:", np.isinf(df[numeric_cols]).values.sum())
preprocessing=ColumnTransformer(transformers=[
    ('nominal',OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'),nominal_cols),
    # ('target',TargetEncoder(cv=5),target_encode),
    ('scalar',StandardScaler(),numeric_cols)
])

Infinite values remaining: 0

In [1663]:
pipe=make_pipeline(preprocessing,LogisticRegression(C=0.001, solver='liblinear', max_iter=1000))

In [1664]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('nominal',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team']),
                                                 ('scalar', StandardScaler(),
                                                  ['runs_to_win',
                                                   'curr_run_rate',
                                                   'req_run_rate',
                                                   'crr_rrr_ratio',
                                                   'balls_remaining',
                                                   'wickets_remaining',
                                                   'batting_average',
                                                   'pressure', 'exp_bowler_eco',
                                                   'exp_bowler_avg'])])),
                ('logisticregression',
                 LogisticRegression(C=0.001, max_iter=1000,
                                    solver='liblinear'))])

In [1665]:
proba_cv=pipe.predict(x_cv)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [1666]:
proba_train=pipe.predict(x_train)

In [1667]:
proba_test=pipe.predict(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [1668]:
from sklearn.metrics import roc_auc_score,f1_score,accuracy_score
print(accuracy_score(proba_train,y_train))
print(accuracy_score(proba_cv,y_cv))
print(accuracy_score(proba_test,y_test))

0.7388954402515723
0.7779450508091833
0.7883591174232818

In [1669]:
# from sklearn.ensemble import RandomForestClassifier,VotingClassifier
# from xgboost import XGBClassifier
# voting_clf=VotingClassifier(estimators=[
#     # ('rf',RandomForestClassifier()),
#      ('lr',LogisticRegression(max_iter=1000)),
#     ('XG',XGBClassifier())],voting='soft')

In [1670]:
# voting_pipe=make_pipeline(preprocessing,voting_clf)

In [1671]:
# from sklearn.model_selection import RandomizedSearchCV
# param_dict = {
#     # XGBoost
#     'votingclassifier__XG__n_estimators': [200, 300, 500],
#     'votingclassifier__XG__max_depth': [3, 4, 6],
#     'votingclassifier__XG__learning_rate': [0.05, 0.1, 0.2],
#     'votingclassifier__XG__subsample': [0.7, 0.8],
#     'votingclassifier__XG__reg_lambda': [1, 5, 10],
#     'votingclassifier__XG__colsample_bytree': [0.7, 0.8],

#     # # RF
#     # 'votingclassifier__rf__n_estimators': [100, 200],
#     # 'votingclassifier__rf__max_depth': [5, 6],
#     # 'votingclassifier__rf__min_samples_leaf': [20, 50],
#     # 'votingclassifier__rf__max_features': ['sqrt'],
# }
# random_search=RandomizedSearchCV(estimator=voting_pipe,param_distributions=param_dict,n_iter=20,cv=5,verbose=2,n_jobs=-1)

In [1672]:
# random_search.fit(x_train,y_train)

In [1673]:
# best_estimator=random_search.best_estimator_
# print("Best_Parameters ",random_search.best_params_)
# print("Best_Estimator",best_estimator)

In [1674]:
# test1=best_estimator.predict(x_test)
# test2=best_estimator.predict(x_train)
# test3=best_estimator.predict(x_cv)

In [1675]:
# print('best_estimator_on_cv: ',accuracy_score(test3,y_cv))
# print('best_estimator_on_train: ',accuracy_score(test2,y_train))
# print('best_estimator_on_test: ',accuracy_score(test1,y_test))

In [1676]:
# import pandas as pd

# xgb_model = best_estimator.named_steps['votingclassifier'].estimators_[2]
# features = best_estimator.named_steps['columntransformer'].get_feature_names_out()

# importance = pd.Series(xgb_model.feature_importances_, index=features).sort_values(ascending=False)
# importance.head(10).plot(kind='barh', title='What Drives a Win?')

In [1677]:
from xgboost import XGBClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder,TargetEncoder,StandardScaler

overfit_cols = ['striker', 'non_striker', 'bowler', 'venue']

x_ttrain = x_train.drop(columns=overfit_cols)
x_ccv    = x_cv.drop(columns=overfit_cols)
x_ttest  = x_test.drop(columns=overfit_cols)

target_encode_modified = []

nominal_cols_modified = ['batting_team','bowling_team']

preprocessing_for_xgb = ColumnTransformer(transformers=[
    ('nominal', OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'), nominal_cols_modified),
    ('target', TargetEncoder(cv=5), target_encode_modified),
    ('scalar', StandardScaler(), numeric_cols)
])

xgb_pipe = make_pipeline(
    preprocessing_for_xgb,
    XGBClassifier(
         n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_lambda=5,
    reg_alpha=1,
    min_child_weight=10,
    gamma=1,
    eval_metric='logloss',
    random_state=42
    )
)

xgb_pipe.fit(x_ttrain, y_train)

print("Train:", accuracy_score(y_train, xgb_pipe.predict(x_ttrain)))
print("CV:   ", accuracy_score(y_cv,    xgb_pipe.predict(x_ccv)))
print("Test: ", accuracy_score(y_test,  xgb_pipe.predict(x_ttest)))

Train: 0.8320435338050315
CV:    0.7724501317275122
Test:  0.7836672584326655

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [1678]:
x_train.columns

Index(['venue', 'batting_team', 'bowling_team', 'striker', 'non_striker',
       'bowler', 'runs_to_win', 'curr_run_rate', 'req_run_rate',
       'crr_rrr_ratio', 'balls_remaining', 'wickets_remaining',
       'batting_average', 'career_strike_rate', 'exp_bowler_eco',
       'exp_bowler_avg', 'pressure'],
      dtype='object')

In [1679]:
x_ttrain.columns

Index(['batting_team', 'bowling_team', 'runs_to_win', 'curr_run_rate',
       'req_run_rate', 'crr_rrr_ratio', 'balls_remaining', 'wickets_remaining',
       'batting_average', 'career_strike_rate', 'exp_bowler_eco',
       'exp_bowler_avg', 'pressure'],
      dtype='object')

In [1681]:
row = pd.DataFrame([{
    'batting_team': 'Kolkata Knight Riders',
    'bowling_team': 'Sunrisers Hyderabad',
    'runs_to_win': 107,
    'curr_run_rate': 11.08,
    'req_run_rate': 11.67,
    'crr_rrr_ratio': 0.95,
    'balls_remaining': 55,
    'wickets_remaining': 7,
    'batting_average': 27.0,
    'career_strike_rate': 135.0,
    'exp_bowler_eco': 7.5,
    'exp_bowler_avg': 25.0,
    'pressure': 11.67-11.08
}])


# prediction
print(xgb_pipe.predict(row))
print(xgb_pipe.predict_proba(row))

[0]
[[0.88671577 0.11328422]]

In [1682]:
row = pd.DataFrame([{
    'batting_team': 'Kolkata Knight Riders',
    'bowling_team': 'Sunrisers Hyderabad',
    'runs_to_win': 107,
    'curr_run_rate': 11.08,
    'req_run_rate': 11.67,
    'crr_rrr_ratio': 0.95,
    'balls_remaining': 55,
    'wickets_remaining': 7,
    'batting_average': 27.0,
    'career_strike_rate': 135.0,
    'exp_bowler_eco': 7.5,
    'exp_bowler_avg': 25.0,
    'pressure': 11.67-11.08
}])


# prediction
print(pipe.predict(row))
print(pipe.predict_proba(row))

[0]
[[0.79380725 0.20619275]]

In [1683]:
row = pd.DataFrame([{
    'batting_team': 'Mumbai Indians',
    'bowling_team': 'Chennai Super Kings',
    'runs_to_win': 48,
    'curr_run_rate': 8.5,
    'req_run_rate': 9.6,
    'crr_rrr_ratio': 0.88,
    'balls_remaining': 30,
    'wickets_remaining': 7,
    'batting_average': 28,
    'career_strike_rate': 140,
    'exp_bowler_eco': 7.2,
    'exp_bowler_avg': 26,
    'pressure': 9.6-8.5
}])
print(xgb_pipe.predict(row))
print(xgb_pipe.predict_proba(row))

[0]
[[0.58360124 0.41639873]]

In [1684]:
row = pd.DataFrame([{
    'batting_team': 'Mumbai Indians',
    'bowling_team': 'Chennai Super Kings',
    'runs_to_win': 48,
    'curr_run_rate': 8.5,
    'req_run_rate': 9.6,
    'crr_rrr_ratio': 0.88,
    'balls_remaining': 30,
    'wickets_remaining': 7,
    'batting_average': 28,
    'career_strike_rate': 140,
    'exp_bowler_eco': 7.2,
    'exp_bowler_avg': 26,
    'pressure': 9.6-8.5
}])
print(pipe.predict(row))
print(pipe.predict_proba(row))

[0]
[[0.6103886 0.3896114]]

In [1685]:
print("Unique Venues:", df['venue'].unique())
print("Unique Strikers:", df['striker'].unique())
print("Unique Non-Strikers:", df['non_striker'].unique())
print("Unique Bowlers:", df['bowler'].unique())

Unique Venues: ['M Chinnaswamy Stadium' 'Punjab Cricket Association Stadium, Mohali'
 'Feroz Shah Kotla' 'Eden Gardens' 'Sawai Mansingh Stadium'
 'Rajiv Gandhi International Stadium, Uppal'
 'MA Chidambaram Stadium, Chepauk' 'Dr DY Patil Sports Academy'
 'Wankhede Stadium' 'Newlands' "St George's Park" 'Kingsmead'
 'SuperSport Park' 'Buffalo Park' 'New Wanderers Stadium'
 'De Beers Diamond Oval' 'OUTsurance Oval' 'Brabourne Stadium'
 'Sardar Patel Stadium, Motera' 'Barabati Stadium'
 'Brabourne Stadium, Mumbai'
 'Vidarbha Cricket Association Stadium, Jamtha'
 'Himachal Pradesh Cricket Association Stadium' 'Nehru Stadium'
 'Holkar Cricket Stadium'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'
 'Subrata Roy Sahara Stadium' 'Maharashtra Cricket Association Stadium'
 'Shaheed Veer Narayan Singh International Stadium'
 'JSCA International Stadium Complex' 'Sheikh Zayed Stadium'
 'Sharjah Cricket Stadium' 'Dubai International Cricket Stadium'
 'Punjab Cricket Association IS Bindra Stadium, Mohali'
 'Saurashtra Cricket Association Stadium' 'Green Park'
 'M.Chinnaswamy Stadium' 'Rajiv Gandhi International Stadium'
 'MA Chidambaram Stadium' 'Punjab Cricket Association IS Bindra Stadium'
 'Arun Jaitley Stadium' 'MA Chidambaram Stadium, Chepauk, Chennai'
 'Wankhede Stadium, Mumbai' 'Narendra Modi Stadium, Ahmedabad'
 'Arun Jaitley Stadium, Delhi' 'Zayed Cricket Stadium, Abu Dhabi'
 'Maharashtra Cricket Association Stadium, Pune'
 'Dr DY Patil Sports Academy, Mumbai' 'Eden Gardens, Kolkata'
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh'
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow'
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad'
 'M Chinnaswamy Stadium, Bengaluru' 'Barsapara Cricket Stadium, Guwahati'
 'Sawai Mansingh Stadium, Jaipur'
 'Himachal Pradesh Cricket Association Stadium, Dharamsala']
Unique Strikers: ['R Dravid' 'W Jaffer' 'V Kohli' 'JH Kallis' 'CL White' 'MV Boucher'
 'B Akhil' 'AA Noffke' 'P Kumar' 'Z Khan' 'SB Joshi' 'K Goel' 'JR Hopes'
 'KC Sangakkara' 'Yuvraj Singh' 'SM Katich' 'IK Pathan' 'G Gambhir'
 'V Sehwag' 'S Dhawan' 'WP Saha' 'BB McCullum' 'RT Ponting' 'SC Ganguly'
 'DJ Hussey' 'Mohammad Hafeez' 'LR Shukla' 'M Kaif' 'YK Pathan'
 'Kamran Akmal' 'SR Watson' 'DS Lehmann' 'RA Jadeja' 'L Ronchi'
 'ST Jayasuriya' 'RV Uthappa' 'SM Pollock' 'DJ Bravo' 'AM Nayar'
 'MA Khote' 'Harbhajan Singh' 'A Nehra' 'GC Smith' 'SK Warne' 'D Salunkhe'
 'Pankaj Singh' 'SS Tiwary' 'DS Kulkarni' 'PA Patel' 'ML Hayden'
 'MS Dhoni' 'DPMD Jayawardene' 'TM Srivastava' 'B Lee' 'B Chipli'
 'LRPL Taylor' 'DW Steyn' 'Salman Butt' 'AB Agarkar' 'BJ Hodge' 'DB Das'
 'Umar Gul' 'AB Dinda' 'I Sharma' 'AB de Villiers' 'AC Gilchrist'
 'VVS Laxman' 'HH Gibbs' 'RG Sharma' 'Shahid Afridi' 'SB Styris'
 'SB Bangar' 'AS Yadav' 'Shoaib Malik' 'KD Karthik' 'R Bhatia'
 'PJ Sangwan' 'VY Mahesh' 'Mohammad Asif' 'GD McGrath' 'SA Asnodkar'
 'S Vidyut' 'SP Fleming' 'SK Raina' 'JA Morkel' 'CK Kapugedera' 'MS Gony'
 'S Badrinath' 'J Arunkumar' 'S Chanderpaul' 'SE Marsh' 'RR Sarwan'
 'PP Chawla' 'VRV Singh' 'DB Ravi Teja' 'Y Venugopal Rao' 'WPUJC Vaas'
 'RP Singh' 'LA Pomersbach' 'MK Tiwary' 'TM Dilshan' 'A Mishra'
 'MF Maharoof' 'SR Tendulkar' 'PP Ojha' 'PM Sarvesh Kumar' 'DJ Thornely'
 'Misbah-ul-Haq' 'DT Patil' 'A Kumble' 'Abdur Razzak' 'LPC Silva' 'H Das'
 'DNT Zoysa' 'Sohail Tanvir' 'DR Smith' 'PR Shah' 'SD Chitnis'
 'CRD Fernando' 'L Balaji' 'M Ntini' 'A Chopra' 'Niraj Patel'
 'Younis Khan' 'M Rawat' 'A Flintoff' 'JDP Oram' 'Joginder Sharma'
 'T Thushara' 'T Henderson' 'AD Mascarenhas' 'MM Patel' 'Kamran Khan'
 'KP Pietersen' 'R Bishnoi' 'R Vinay Kumar' 'CH Gayle' 'JD Ryder'
 'KV Sharma' 'Yashpal Singh' 'JP Duminy' 'M Manhas' 'RJ Quiney' 'AS Raut'
 'AN Ghosh' 'BAW Mendis' 'PC Valthaty' 'SP Goswami' 'RE van der Merwe'
 'MK Pandey' 'SK Trivedi' 'MN van Wyk' 'LA Carseldine' 'NV Ojha'
 'SM Harwood' 'DA Warner' 'S Sohal' 'TL Suman' 'RJ Harris' 'Shoaib Ahmed'
 'RR Powar' 'S Sreesanth' 'RR Raje' 'WA Mota' 'M Morkel' 'AM Rahane'
 'A Symonds' 'YV Takawale' 'C Nanda' 'SL Malinga' 'J Botha' 'A Singh'
 'SS Shaikh' 'AA Bilakhia' 'Anirudh Singh' 'Jaskaran Singh'
 'AA Jhunjhunwala' 'P Dogra' 'A Uniyal' 'CA Pujara' 'M Vijay' 'JM Kemp'
 'R Ashwin' 'M Muralitharan' 'S Tyagi' 'OA Shah' 'AD Mathews'
 'RS Gavaskar' 'SE Bond' 'M Kartik' 'S Ladda' 'DP Nannes' 'RS Bopara'
 'MS Bisla' 'AB Barath' 'Bipul Sharma' 'EJG Morgan' 'MC Henriques'
 'Y Nagar' 'UT Yadav' 'KA Pollard' 'R Sathish' 'GJ Bailey' 'J Theron'
 'SJ Srivastava' 'R McLaren' 'MJ Lumb' 'FY Fazal' 'KB Arun Karthik'
 'MD Mishra' 'KAJ Roach' 'Mandeep Singh' 'AC Voges' 'S Narwal' 'SW Tait'
 'R Sharma' 'A Mithun' 'KP Appanna' 'AT Rayudu' 'AN Ahmed'
 'PD Collingwood' 'KM Jadhav' 'DL Vettori' 'S Sriram' 'AP Dole'
 'AB McDonald' 'MR Marsh' 'B Sumanth' 'Harmeet Singh' 'Iqbal Abdulla'
 'AG Paunikar' 'MA Agarwal' 'AUK Pathan' 'IR Jaggi' 'DT Christian'
 'AL Menaria' 'DJ Jacobs' 'Sunny Singh' 'WD Parnell' 'JJ van der Wath'
 'R Ninan' 'S Aravind' 'MS Wade' 'AJ Finch' 'Shakib Al Hasan' 'STR Binny'
 'DH Yagnik' 'MEK Hussey' 'S Anirudha' 'S Randiv' 'DE Bollinger'
 'NL McCullum' 'JE Taylor' 'AC Thomas' 'J Syed Mohammad' 'RV Gomez'
 'NLTC Perera' 'TR Birt' 'TD Paine' 'M Klinger' 'SB Wagh' 'L Ablish'
 'CA Ingram' 'CJ Ferguson' 'AC Blizzard' 'VR Aaron' 'CK Langeveldt'
 'Y Gnaneswara Rao' 'BA Bhatt' 'JEC Franklin' 'RE Levi' 'SA Yadav'
 'JP Faulkner' 'GJ Maxwell' 'DAJ Bracewell' 'DJ Harris' 'Ankit Sharma'
 'SP Narine' 'HV Patel' 'KK Cooper' 'AA Chavan' 'GB Hogg' 'F du Plessis'
 'RN ten Doeschate' 'MN Samuels' 'SPD Smith' 'B Kumar' 'P Negi'
 'RJ Peterson' 'KMDN Kulasekara' 'MJ Clarke' 'A Ashish Reddy' 'N Saini'
 'Azhar Mahmood' 'Gurkeerat Singh' 'PA Reddy' 'AP Majumdar' 'K Upadhyay'
 'UBT Chand' 'AD Russell' 'CA Lynn' 'Harpreet Singh' 'AG Murtaza'
 'Sunny Gupta' 'MC Juneja' 'B Laughlin' 'AS Rajpoot' 'M Vohra'
 'Mohammed Shami' 'BMAJ Mendis' 'S Nadeem' 'GH Vihari' 'CH Morris'
 'SV Samson' 'SMSM Senanayake' 'KL Rahul' 'R Rampaul' 'R Dhawan'
 'MG Johnson' 'DA Miller' 'LJ Wright' 'IC Pandey' 'KW Richardson'
 'BJ Rohrer' 'DJG Sammy' 'MM Sharma' 'UA Birla' 'Parvez Rasool' 'P Awana'
 'S Kaul' 'CM Gautam' 'Sachin Baby' 'PV Tambe' 'AP Tare' 'NM Coulter-Nile'
 'BB Samantray' 'CJ Anderson' 'NJ Maddinson' 'AR Patel' 'JDS Neesham'
 'JD Unadkat' 'TG Southee' 'KK Nair' 'Q de Kock' 'BR Dunk' 'RR Rossouw'
 'MA Starc' 'S Rana' 'YS Chahal' 'LMP Simmons' 'R Shukla' 'Imran Tahir'
 'R Tewatia' 'VS Malik' 'Karanveer Singh' 'SS Iyer' 'Anureet Singh'
 'KS Williamson' 'SA Abbott' 'DJ Hooda' 'J Suchith' 'D Wiese' 'SN Khan'
 'HH Pandya' 'MJ McClenaghan' 'Sandeep Sharma' 'PJ Cummins' 'Ishan Kishan'
 'JC Buttler' 'AD Nath' 'M Ashwin' 'KH Pandya' 'NS Naik' 'RR Pant'
 'JO Holder' 'MP Stoinis' 'Swapnil Singh' 'UT Khawaja' 'TM Head'
 'SW Billings' 'CR Brathwaite' 'JJ Bumrah' 'HM Amla' 'F Behardien'
 'N Rana' 'S Kaushik' 'BCJ Cutting' 'KJ Abbott' 'KC Cariappa' 'BB Sran'
 'C Munro' 'CJ Jordan' 'TS Mills' 'A Choudhary' 'BA Stokes' 'RA Tripathi'
 'DL Chahar' 'A Zampa' 'AF Milne' 'S Badree' 'AJ Tye' 'K Rabada'
 'Basil Thampi' 'DM Bravo' 'SP Jackson' 'MJ Guptill' 'C de Grandhomme'
 'CR Woakes' 'Washington Sundar' 'Rashid Khan' 'Kuldeep Yadav' 'TA Boult'
 'MA Wood' 'RK Singh' 'V Shankar' 'JJ Roy' 'Mohammed Siraj' 'H Klaasen'
 'K Gowtham' 'S Gopal' 'RK Bhui' 'JC Archer' 'PP Shaw' 'LE Plunkett'
 'E Lewis' 'M Markande' 'Mustafizur Rahman' 'Mujeeb Ur Rahman'
 'Shubman Gill' 'Shivam Mavi' 'MK Lomror' 'DJM Short' 'DR Shorey'
 'AD Hales' 'MM Ali' 'TK Curran' 'M Prasidh Krishna' 'SN Thakur'
 'Rasikh Salam' 'SO Hetmyer' 'S Dube' 'JM Bairstow' 'P Ray Barman'
 'Avesh Khan' 'S Lamichhane' 'Mohammad Nabi' 'SM Curran' 'SD Lad'
 'AS Joseph' 'MJ Santner' 'LS Livingstone' 'Abhishek Sharma' 'KK Ahmed'
 'AJ Turner' 'R Parag' 'SE Rutherford' 'N Pooran' 'GC Viljoen' 'RD Chahar'
 'P Simran Singh' 'PK Garg' 'T Natarajan' 'RD Gaikwad' 'D Padikkal'
 'JR Philippe' 'NA Saini' 'A Nortje' 'Ravi Bishnoi' 'KL Nagarkoti'
 'Abdul Samad' 'I Udana' 'YBK Jaiswal' 'SS Cottrell' 'Arshdeep Singh'
 'Kartik Tyagi' 'N Jagadeesan' 'T Banton' 'CV Varun' 'AT Carey'
 'TU Deshpande' 'DR Sams' 'RM Patidar' 'Shahbaz Ahmed' 'KA Jamieson'
 'Virat Singh' 'Lalit Yadav' 'Anmolpreet Singh' 'VR Iyer' 'AK Markram'
 'T Shamsi' 'M Shahrukh Khan' 'GD Phillips' 'Harpreet Brar' 'KS Bharat'
 'GHS Garton' 'Anuj Rawat' 'C Sakariya' 'LH Ferguson' 'TL Seifert'
 'R Powell' 'R Shepherd' 'A Badoni' 'Tilak Varma' 'TH David' 'D Pretorius'
 'Mukesh Choudhary' 'Umran Malik' 'DJ Willey' 'B Sai Sudharsan'
 'PVD Chameera' 'SS Prabhudessai' 'PWH de Silva' 'Akash Deep'
 'JR Hazlewood' 'D Brevis' 'HE van der Dussen' 'KR Sen' 'FA Allen'
 'A Manohar' 'PBB Rajapaksa' 'JM Sharma' 'Shashank Singh' 'B Indrajith'
 'DP Conway' 'Simarjeet Singh' 'M Theekshana' 'AS Roy' 'Harshit Rana'
 'Fazalhaq Farooqi' 'RV Patel' 'Ramandeep Singh' 'K Kartikeya'
 'RP Meredith' 'KS Sharma' 'Mohsin Khan (2)' 'M Jansen' 'T Stubbs'
 'R Sanjay Yadav' 'A Tomar' 'Rahmanullah Gurbaz' 'Aman Hakim Khan'
 'HC Brook' 'AU Rashid' 'KR Mayers' 'Dhruv Jurel' 'MG Bracewell'
 'Abishek Porel' 'Mukesh Kumar' 'C Green' 'YV Dhull' 'N Wadhera'
 'Atharva Taide' 'MW Short' 'NT Ellis' 'Abdul Basith' 'Arjun Tendulkar'
 'JP Behrendorff' 'Vijaykumar Vyshak' 'Sikandar Raza' 'PD Salt'
 'Naveen-ul-Haq' 'Noor Ahmad' 'PN Mankad' 'P Dubey' 'JE Root' 'KM Asif'
 'Sanvir Singh' 'Vishnu Vinod' 'VG Arora' 'MD Shanaka' 'DG Nalkande']
Unique Non-Strikers: ['W Jaffer' 'R Dravid' 'V Kohli' 'JH Kallis' 'CL White' 'MV Boucher'
 'B Akhil' 'AA Noffke' 'P Kumar' 'Z Khan' 'SB Joshi' 'JR Hopes' 'K Goel'
 'KC Sangakkara' 'Yuvraj Singh' 'SM Katich' 'IK Pathan' 'V Sehwag'
 'G Gambhir' 'S Dhawan' 'BB McCullum' 'WP Saha' 'RT Ponting' 'SC Ganguly'
 'DJ Hussey' 'Mohammad Hafeez' 'LR Shukla' 'Kamran Akmal' 'YK Pathan'
 'SR Watson' 'DS Lehmann' 'RA Jadeja' 'ST Jayasuriya' 'L Ronchi'
 'RV Uthappa' 'SM Pollock' 'DJ Bravo' 'AM Nayar' 'MA Khote'
 'Harbhajan Singh' 'A Nehra' 'GC Smith' 'M Kaif' 'SK Warne' 'D Salunkhe'
 'Pankaj Singh' 'SS Tiwary' 'DS Kulkarni' 'ML Hayden' 'PA Patel'
 'MS Dhoni' 'DPMD Jayawardene' 'TM Srivastava' 'B Lee' 'B Chipli'
 'LRPL Taylor' 'DW Steyn' 'Salman Butt' 'AB Agarkar' 'BJ Hodge' 'DB Das'
 'Umar Gul' 'I Sharma' 'AB Dinda' 'AB de Villiers' 'VVS Laxman'
 'AC Gilchrist' 'HH Gibbs' 'RG Sharma' 'SB Styris' 'AS Yadav' 'SB Bangar'
 'Shoaib Malik' 'KD Karthik' 'R Bhatia' 'PJ Sangwan' 'VY Mahesh'
 'Mohammad Asif' 'GD McGrath' 'SA Asnodkar' 'Shahid Afridi' 'SP Fleming'
 'S Vidyut' 'SK Raina' 'JA Morkel' 'CK Kapugedera' 'S Badrinath' 'MS Gony'
 'S Chanderpaul' 'J Arunkumar' 'SE Marsh' 'RR Sarwan' 'PP Chawla'
 'S Sreesanth' 'DB Ravi Teja' 'Y Venugopal Rao' 'WPUJC Vaas' 'RP Singh'
 'LA Pomersbach' 'MK Tiwary' 'TM Dilshan' 'A Mishra' 'MF Maharoof'
 'SR Tendulkar' 'DP Vijaykumar' 'DJ Thornely' 'Misbah-ul-Haq' 'DT Patil'
 'A Kumble' 'Abdur Razzak' 'LPC Silva' 'DNT Zoysa' 'H Das' 'Sohail Tanvir'
 'DR Smith' 'PR Shah' 'SD Chitnis' 'CRD Fernando' 'M Ntini' 'A Chopra'
 'Niraj Patel' 'Younis Khan' 'M Rawat' 'A Flintoff' 'JDP Oram'
 'Joginder Sharma' 'T Henderson' 'Kamran Khan' 'KP Pietersen' 'R Bishnoi'
 'R Vinay Kumar' 'CH Gayle' 'KV Sharma' 'L Balaji' 'M Muralitharan'
 'Yashpal Singh' 'JP Duminy' 'M Manhas' 'RJ Quiney' 'AS Raut' 'AN Ghosh'
 'BAW Mendis' 'PC Valthaty' 'SP Goswami' 'RE van der Merwe' 'MK Pandey'
 'AD Mascarenhas' 'SK Trivedi' 'MN van Wyk' 'RR Powar' 'LA Carseldine'
 'NV Ojha' 'SM Harwood' 'DA Warner' 'S Sohal' 'TL Suman' 'RJ Harris'
 'Shoaib Ahmed' 'PP Ojha' 'RR Raje' 'WA Mota' 'M Morkel' 'MM Patel'
 'JD Ryder' 'AM Rahane' 'A Symonds' 'YV Takawale' 'SL Malinga' 'J Botha'
 'SS Shaikh' 'AA Bilakhia' 'Anirudh Singh' 'Jaskaran Singh'
 'AA Jhunjhunwala' 'P Dogra' 'CA Pujara' 'M Vijay' 'JM Kemp' 'R Ashwin'
 'S Tyagi' 'OA Shah' 'AD Mathews' 'RS Gavaskar' 'SE Bond' 'M Kartik'
 'S Ladda' 'DP Nannes' 'MS Bisla' 'RS Bopara' 'AB Barath' 'Bipul Sharma'
 'EJG Morgan' 'MC Henriques' 'Y Nagar' 'UT Yadav' 'KA Pollard' 'R Sathish'
 'GJ Bailey' 'J Theron' 'SJ Srivastava' 'R McLaren' 'MJ Lumb' 'FY Fazal'
 'KB Arun Karthik' 'T Thushara' 'MD Mishra' 'KAJ Roach' 'Mandeep Singh'
 'AC Voges' 'S Narwal' 'SW Tait' 'R Sharma' 'A Mithun' 'KP Appanna'
 'Harmeet Singh' 'AT Rayudu' 'AN Ahmed' 'PD Collingwood' 'KM Jadhav'
 'DL Vettori' 'S Sriram' 'AP Dole' 'AB McDonald' 'MR Marsh' 'B Sumanth'
 'AG Paunikar' 'MA Agarwal' 'AUK Pathan' 'IR Jaggi' 'DT Christian'
 'AL Menaria' 'DJ Jacobs' 'Sunny Singh' 'WD Parnell' 'R Ninan' 'S Aravind'
 'JJ van der Wath' 'MS Wade' 'AJ Finch' 'S Nadeem' 'Shakib Al Hasan'
 'Iqbal Abdulla' 'STR Binny' 'DH Yagnik' 'MEK Hussey' 'S Anirudha'
 'S Randiv' 'DE Bollinger' 'NL McCullum' 'JE Taylor' 'AC Thomas'
 'J Syed Mohammad' 'NLTC Perera' 'TR Birt' 'TD Paine' 'Harpreet Singh'
 'M Klinger' 'SB Wagh' 'L Ablish' 'CJ Ferguson' 'A Singh' 'AC Blizzard'
 'CA Ingram' 'VR Aaron' 'CK Langeveldt' 'Y Gnaneswara Rao' 'BA Bhatt'
 'JEC Franklin' 'RE Levi' 'SA Yadav' 'JP Faulkner' 'GJ Maxwell'
 'DAJ Bracewell' 'DJ Harris' 'Ankit Sharma' 'TP Sudhindra' 'HV Patel'
 'KK Cooper' 'AA Chavan' 'GB Hogg' 'F du Plessis' 'RN ten Doeschate'
 'MN Samuels' 'SPD Smith' 'B Kumar' 'P Negi' 'RJ Peterson'
 'KMDN Kulasekara' 'MJ Clarke' 'A Ashish Reddy' 'N Saini' 'Azhar Mahmood'
 'Gurkeerat Singh' 'PA Reddy' 'AP Majumdar' 'K Upadhyay' 'UBT Chand'
 'AD Russell' 'CA Lynn' 'AG Murtaza' 'P Parameswaran' 'Sunny Gupta'
 'MC Juneja' 'B Laughlin' 'AS Rajpoot' 'M Vohra' 'Mohammed Shami'
 'SP Narine' 'BMAJ Mendis' 'GH Vihari' 'CH Morris' 'SV Samson'
 'SMSM Senanayake' 'KL Rahul' 'R Rampaul' 'R Dhawan' 'MG Johnson'
 'DA Miller' 'LJ Wright' 'KW Richardson' 'BJ Rohrer' 'DJG Sammy'
 'UA Birla' 'Parvez Rasool' 'P Awana' 'Sandeep Sharma' 'S Kaul'
 'CM Gautam' 'Sachin Baby' 'PV Tambe' 'AP Tare' 'NM Coulter-Nile'
 'BB Samantray' 'MM Sharma' 'CJ Anderson' 'NJ Maddinson' 'AR Patel'
 'JDS Neesham' 'JD Unadkat' 'TG Southee' 'MA Starc' 'KK Nair' 'Q de Kock'
 'BR Dunk' 'RR Rossouw' 'S Rana' 'YS Chahal' 'LMP Simmons' 'R Shukla'
 'Imran Tahir' 'R Tewatia' 'VS Malik' 'Karanveer Singh' 'SS Iyer'
 'DJ Muthuswami' 'Anureet Singh' 'KS Williamson' 'SA Abbott' 'DJ Hooda'
 'J Suchith' 'D Wiese' 'SN Khan' 'JJ Bumrah' 'HH Pandya' 'BE Hendricks'
 'Ishan Kishan' 'MJ McClenaghan' 'JC Buttler' 'AD Nath' 'KH Pandya'
 'NS Naik' 'RR Pant' 'JO Holder' 'S Kaushik' 'MP Stoinis' 'Swapnil Singh'
 'UT Khawaja' 'TM Head' 'SW Billings' 'CR Brathwaite' 'HM Amla'
 'F Behardien' 'N Rana' 'BCJ Cutting' 'KJ Abbott' 'KC Cariappa' 'BB Sran'
 'C Munro' 'CJ Jordan' 'TS Mills' 'A Choudhary' 'BA Stokes' 'PJ Cummins'
 'RA Tripathi' 'DL Chahar' 'A Zampa' 'AF Milne' 'S Badree' 'AJ Tye'
 'Basil Thampi' 'K Rabada' 'DM Bravo' 'SP Jackson' 'MJ Guptill'
 'C de Grandhomme' 'CR Woakes' 'Washington Sundar' 'Rashid Khan'
 'Kuldeep Yadav' 'TA Boult' 'MA Wood' 'RK Singh' 'V Shankar' 'B Stanlake'
 'JJ Roy' 'Mohammed Siraj' 'H Klaasen' 'K Gowtham' 'S Gopal' 'JC Archer'
 'PP Shaw' 'LE Plunkett' 'E Lewis' 'M Markande' 'Mustafizur Rahman'
 'Mujeeb Ur Rahman' 'Shubman Gill' 'MK Lomror' 'DJM Short' 'DR Shorey'
 'AD Hales' 'MM Ali' 'TK Curran' 'M Prasidh Krishna' 'SN Thakur'
 'Shivam Mavi' 'Rasikh Salam' 'SO Hetmyer' 'S Dube' 'JM Bairstow'
 'P Ray Barman' 'Avesh Khan' 'Mohammad Nabi' 'SM Curran' 'SD Lad'
 'AS Joseph' 'RD Chahar' 'LS Livingstone' 'RK Bhui' 'Abhishek Sharma'
 'AJ Turner' 'KMA Paul' 'R Parag' 'SE Rutherford' 'N Pooran' 'MJ Santner'
 'P Simran Singh' 'M Ashwin' 'PK Garg' 'T Natarajan' 'D Padikkal'
 'JR Philippe' 'NA Saini' 'RD Gaikwad' 'Ravi Bishnoi' 'KL Nagarkoti'
 'Abdul Samad' 'I Udana' 'Kartik Tyagi' 'SS Cottrell' 'YBK Jaiswal'
 'N Jagadeesan' 'T Banton' 'CV Varun' 'AT Carey' 'TU Deshpande' 'A Nortje'
 'RM Patidar' 'Shahbaz Ahmed' 'KA Jamieson' 'Virat Singh' 'KK Ahmed'
 'C Sakariya' 'Lalit Yadav' 'DR Sams' 'Anmolpreet Singh' 'VR Iyer'
 'AK Markram' 'T Shamsi' 'LH Ferguson' 'M Shahrukh Khan' 'FA Allen'
 'GD Phillips' 'Harpreet Brar' 'KS Bharat' 'GHS Garton' 'Anuj Rawat'
 'TL Seifert' 'R Shepherd' 'A Badoni' 'Tilak Varma' 'TH David' 'R Powell'
 'D Pretorius' 'Mukesh Choudhary' 'DJ Willey' 'B Sai Sudharsan'
 'PVD Chameera' 'SS Prabhudessai' 'PWH de Silva' 'JR Hazlewood' 'D Brevis'
 'HE van der Dussen' 'HR Shokeen' 'PBB Rajapaksa' 'JM Sharma'
 'Arshdeep Singh' 'Shashank Singh' 'M Jansen' 'B Indrajith' 'DP Conway'
 'Simarjeet Singh' 'Fazalhaq Farooqi' 'Ramandeep Singh' 'K Kartikeya'
 'KS Sharma' 'Mohsin Khan (2)' 'Umran Malik' 'T Stubbs' 'A Tomar'
 'Rahmanullah Gurbaz' 'Aman Hakim Khan' 'HC Brook' 'AU Rashid' 'KR Mayers'
 'Dhruv Jurel' 'MG Bracewell' 'Akash Deep' 'Abishek Porel' 'Mukesh Kumar'
 'C Green' 'N Wadhera' 'MW Short' 'NT Ellis' 'PN Mankad' 'Arjun Tendulkar'
 'JP Behrendorff' 'Vijaykumar Vyshak' 'Atharva Taide' 'Sikandar Raza'
 'PD Salt' 'RV Patel' 'Naveen-ul-Haq' 'A Manohar' 'Noor Ahmad' 'P Dubey'
 'JE Root' 'Sanvir Singh' 'Vishnu Vinod' 'YV Dhull' 'VG Arora'
 'MD Shanaka']
Unique Bowlers: ['AB Dinda' 'I Sharma' 'AB Agarkar' 'SC Ganguly' 'LR Shukla' 'JDP Oram'
 'MS Gony' 'M Muralitharan' 'P Amarnath' 'Joginder Sharma' 'MM Patel'
 'SR Watson' 'SK Trivedi' 'SK Warne' 'YK Pathan' 'D Salunkhe' 'WPUJC Vaas'
 'RP Singh' 'SB Styris' 'SB Bangar' 'A Symonds' 'PP Ojha' 'B Lee'
 'S Sreesanth' 'JR Hopes' 'IK Pathan' 'PP Chawla' 'WA Mota'
 'Shahid Afridi' 'D Kalyankrishna' 'VRV Singh' 'DJ Hussey'
 'Mohammad Hafeez' 'M Kartik' 'GD McGrath' 'Mohammad Asif' 'MF Maharoof'
 'VY Mahesh' 'Shoaib Malik' 'R Bhatia' 'JA Morkel' 'DL Vettori' 'V Sehwag'
 'Sohail Tanvir' 'M Ntini' 'Gagandeep Singh' 'DW Steyn' 'Z Khan' 'P Kumar'
 'A Kumble' 'JH Kallis' 'SM Pollock' 'A Nehra' 'DJ Bravo' 'DS Kulkarni'
 'ST Jayasuriya' 'DJ Thornely' 'RR Raje' 'SK Raina' 'S Vidyut'
 'PJ Sangwan' 'Umar Gul' 'DP Vijaykumar' 'Y Venugopal Rao' 'CK Kapugedera'
 'L Balaji' 'R Vinay Kumar' 'V Kohli' 'Shoaib Akhtar' 'Iqbal Abdulla'
 'A Mishra' 'RA Jadeja' 'CRD Fernando' 'AM Nayar' 'B Akhil' 'Yuvraj Singh'
 'RG Sharma' 'Pankaj Singh' 'RR Powar' 'DR Smith' 'PM Sarvesh Kumar'
 'SL Malinga' 'Harbhajan Singh' 'JD Ryder' 'YA Abdulla' 'VS Malik'
 'CH Gayle' 'MC Henriques' 'A Flintoff' 'RS Bopara' 'FH Edwards'
 'Harmeet Singh' 'DP Nannes' 'AM Salvi' 'MK Tiwary' 'AD Mascarenhas'
 'Kamran Khan' 'KP Appanna' 'SR Tendulkar' 'TM Dilshan' 'BJ Hodge'
 'K Goel' 'Shoaib Ahmed' 'S Tyagi' 'GR Napier' 'RE van der Merwe'
 'SB Jakati' 'A Singh' 'SM Harwood' 'RJ Harris' 'TL Suman' 'D du Preez'
 'JP Duminy' 'C Nanda' 'SS Sarkar' 'BAW Mendis' 'AD Mathews' 'J Botha'
 'AB McDonald' 'Y Nagar' 'T Henderson' 'T Thushara' 'R Ashwin' 'RA Shaikh'
 'CK Langeveldt' 'R McLaren' 'AG Murtaza' 'R Sathish' 'Jaskaran Singh'
 'SW Tait' 'A Uniyal' 'Bipul Sharma' 'JM Kemp' 'KA Pollard' 'UT Yadav'
 'AC Voges' 'R Sharma' 'SJ Srivastava' 'J Theron' 'SE Bond' 'NLTC Perera'
 'S Narwal' 'PD Collingwood' 'S Ladda' 'MB Parmar' 'DE Bollinger'
 'JD Unadkat' 'AP Dole' 'M Morkel' 'AJ Finch' 'FY Fazal' 'MR Marsh'
 'STR Binny' 'TG Southee' 'S Randiv' 'DT Christian' 'RV Gomez'
 'NJ Rimmington' 'RN ten Doeschate' 'S Nadeem' 'A Mithun' 'AUK Pathan'
 'AL Menaria' 'ND Doshi' 'AC Thomas' 'SB Wagh' 'WD Parnell'
 'AA Jhunjhunwala' 'S Dhawan' 'BA Bhatt' 'PC Valthaty' 'AN Ahmed'
 'VR Aaron' 'JE Taylor' 'S Aravind' 'J Syed Mohammad' 'NL McCullum'
 'P Parameswaran' 'I Malhotra' 'B Chipli' 'Anand Rajan' 'JEC Franklin'
 'Shakib Al Hasan' 'MN Samuels' 'B Kumar' 'KK Cooper' 'AA Chavan'
 'HV Patel' 'F du Plessis' 'Ankit Sharma' 'CL White' 'RR Bhatkal'
 'GB Hogg' 'KMDN Kulasekara' 'V Pratap Singh' 'LJ Wright' 'P Awana'
 'Azhar Mahmood' 'A Ashish Reddy' 'SP Narine' 'BW Hilfenhaus' 'M de Lange'
 'MJ Clarke' 'SPD Smith' 'TP Sudhindra' 'A Chandila' 'S Badree' 'R Shukla'
 'MG Johnson' 'GH Vihari' 'Harmeet Singh (2)' 'JP Faulkner' 'S Kaul'
 'R Dhawan' 'R Rampaul' 'SMSM Senanayake' 'KV Sharma' 'MM Sharma'
 'CH Morris' 'JJ Bumrah' 'DJG Sammy' 'BMAJ Mendis' 'P Suyal' 'K Upadhyay'
 'P Negi' 'BJ Rohrer' 'JO Holder' 'IC Pandey' 'Sandeep Sharma'
 'AC Gilchrist' 'Mohammed Shami' 'JDS Neesham' 'KW Richardson' 'PV Tambe'
 'AR Patel' 'GJ Maxwell' 'CJ Anderson' 'MA Starc' 'YS Chahal' 'R Tewatia'
 'Shivam Sharma' 'Imran Tahir' 'LMP Simmons' 'BCJ Cutting' 'K Santokie'